language: node
sudo: false
script:
- node -v
before_install:
- openssl aes-256-cbc -K $encrypted_9523ba30eeb5_key -iv $encrypted_9523ba30eeb5_iv
  -in the-wilson-post-3ab855a12d9c.json.enc -out the-wilson-post-3ab855a12d9c.json
  -d
deploy:
  provider: gae
  keyfile: "the-wilson-post-3ab855a12d9c.json"
  project: "the-wilson-post"
  skip_cleanup: true
